test "is saddled":
	spawn a horse at (spawn of world "world"):
		set {_h} to event-entity

	spawn a pig at (spawn of world "world"):
		set {_p} to event-entity

	equip {_h} and {_p} with saddle
	assert {_h} and {_p} are saddled with "equipping a horse or steerable with a saddle should do exactly that"

	unequip saddle from {_h} and {_p}
	assert {_h} and {_p} aren't saddled with "unequipping a saddle from a horse or steerable should do exactly that"
