test "colour complements":

	set {_bluesComplement} to complement of blue
	set {_bluesHslComplement} to hsl complement of blue
	set {_bluesComplementsComplement} to complement of {_bluesComplement}
	set {_bluesHslComplementsHslComplement} to hsl complement of {_bluesHslComplement}
	set {_trueBlacksComplement} to complement of rgb(0, 0, 0)
	set {_trueBlacksHslComplement} to hsl complement of rgb(0, 0, 0)
	set {_trueWhitesComplement} to complement of rgb(255, 255, 255)
	set {_trueWhitesHslComplement} to hsl complement of rgb(255, 255, 255)

	assert hex code of {_bluesComplement} is "#C3BB55" with "complement of blue was incorrect"
	assert hex code of {_bluesHslComplement} is "#AAA23C" with "hsl complement of blue was incorrect"
	assert hex code of {_bluesComplementsComplement} is hex code of blue with "complement of blue's complement was incorrect"
	assert hex code of {_bluesHslComplementsHslComplement} is hex code of blue with "hsl complement of blue's hsl complement was incorrect"
	assert hex code of {_trueBlacksComplement} is "#FFFFFF" with "complement of true black was incorrect"
	assert hex code of {_trueBlacksHslComplement} is "#000000" with "hsl complement of true black was incorrect"
	assert hex code of {_trueWhitesComplement} is "#000000" with "complement of true white was incorrect"
	assert hex code of {_trueWhitesHslComplement} is "#FFFFFF" with "hsl complement of true white was incorrect"

	assert complement of test block is not set with "complement of an invalid type should return null"
	assert complement of "x" is not set with "complement of an invalid type should return null"
	assert complement of {_x} is not set with "complement of an invalid type should return null"
